FROM golang:1.15 AS build-env

WORKDIR /go/bin/go-icn

COPY . .

WORKDIR /go/bin/go-icn/content-provider

RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon

EXPOSE 8080

ENTRYPOINT CompileDaemon --build="go build" --command=./content-provider